---
- name: build new machine
  hosts: host3
  become: yes
  gather_facts: no
  roles: 
  - role: libvirt-guest
    # !!!
    ignore_errors: yes

- name: check new machine
  hosts: provisioner
  become: no
  gather_facts: no
  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30

