# run
#   ansible-playbook  --ask-become-pass  delete.yml
#   ansible-playbook  --become-password-file=~/my_pass --extra-var='host=some_host' delete.yml
#
# remove the virtual machine
- hosts: localhost
  become: yes
  vars:
    host: satellite1
  tasks:  

  # https://github.com/ansible-collections/community.libvirt/issues/40
  - name: delete NVRAM file
    file:
      name: "/var/lib/libvirt/qemu/nvram/{{ host }}_VARS.fd"
      state: absent

  - name: pull the plug
    community.libvirt.virt:
      name: "{{ host }}"
      state: destroyed
  
  - name: delete libvirt's domain
    community.libvirt.virt:
      name: "{{ host }}"
      command: undefine
  
  #https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-storage_volume_commands-deleting_storage_volumes
  - name: delete libvirt's volume
    ansible.builtin.command: 
      cmd: "virsh vol-delete {{ host }}.qcow2 images"

