#
- name: build the satellite application
  hosts: provisioner
  become: yes
  gather_facts: no
  tasks: 
  - name: I got nothing
    debug: 
      msg: err.....


# server certificate missing from this. 
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html-single/installing_satellite_server_in_a_connected_network_environment/index#Configuring_Server_with_a_Custom_SSL_Certificate_satellite
# katello-certs-check \
#   -c /etc/pki/tls/certs/satellite1.lab.example.com.pem \
#   -k /etc/pki/tls/private/satellite1.lab.example.com.key  \
#   -b /etc/pki/ca-trust/source/anchors/ca-certificate.pem
#
# something like 
#
#  register and update
# subscription-manager register someguy somepass
# dnf update
# systemctl reboot
#
#  find the Satellite pool ID and subscribe
# subscription-manager list --all --available > subscription-manager-list--all--available.txt
# grep 'Red Hat Satellite Infrastructure Subscription' subscription-manager-list--all--available.txt 
# subscription-manager attach --pool=12345
# or maybe
# subscription-manager list  --all --available  \
#   --matches 'Red Hat Satellite Infrastructure Subscription' | grep 'Pool ID'
#
#  use RHEL 8 and Satellite 6.11 repos 
# subscription-manager repos --list  > subscription-manager-repos--list.txt
# grep satellite subscription-manager-repos--list.txt | grep 6.11
# subscription-manager repos --disable "*"
# subscription-manager repos \
#   --enable=rhel-8-for-x86_64-baseos-rpms \
#   --enable=rhel-8-for-x86_64-appstream-rpms \
#   --enable=satellite-6.11-for-rhel-8-x86_64-rpms \
#   --enable=satellite-maintenance-6.11-for-rhel-8-x86_64-rpms
#
#  install RPM packages
# dnf install sos
# yum module enable satellite:el8
# yum install satellite
#
# DNS
#
# firewall
# firewall-cmd --info-service=RH-Satellite-6
# firewall-cmd --permanent --add-service=RH-Satellite-6
# firewall-cmd --permanent --add-service=https
# firewall-cmd --reload
#
# set up Satellite
# satellite-installer \
#   --scenario satellite \
#   --foreman-initial-admin-username someguy \
#   --foreman-initial-admin-password somepass \
#   --certs-server-cert    "/etc/pki/tls/certs/satellite1.lab.example.com.pem" \
#   --certs-server-key     "/etc/pki/tls/private/satellite1.lab.example.com.key" \
#   --certs-server-ca-cert "/etc/pki/ca-trust/source/anchors/ca-certificate.pem"

# checks
# hostnamectl status
# getenforce
# systemctl status chronyd
# ping -c1 localhost
# ping -c1 $(hostname -s)
# ping -c1 $(hostname -f)
# dig -x 1.2.3.4

