# run
#   ansible-playbook  --ask-become-pass remove.yml
# or
#   ansible-playbook  --become-password-file=~/my-pass --extra-var="host=kvm-guest" remove.yml
---
- name: remove virt domain
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:

  # fails if domain is not running
  - name: pull the plug
    command:
      cmd: "virsh destroy {{ host }}"
    ignore_errors: yes

  - name: delete everything
    command:
      cmd: "virsh undefine --nvram --remove-all-storage {{ host }}"


